api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserActionViewSet, ProductViewSet, BidViewSet, UserViewSet, recommend_products

router = DefaultRouter()
router.register(r'useractions', UserActionViewSet)
router.register(r'product', ProductViewSet)
router.register(r'bid', BidViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('recommend/<int:user_id>/', recommend_products, name='recommend_products'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

#거래내역 ( 등록중 상품 목록, 입찰 참여중 상품 목록, 입찰 완료 상품 목록)
#(상품 등록) -> 등록중 상품 목록에 추가
#입찰 참여 - > 입찰가 입력 (-> 마일리지 차감) -> 입찰 참여중 목록에 올라감(product table 참조)
#입찰 완료 -> Bid 테이블에 새로운 행 생성 -> 입찰 완료 상품 목록에 추가 
urlpatterns = [
    path('purchase_history/', views.purchase_history, name='purchase_history'),
    path("purchase_history/ing/<int:pk>/", views.purchase_history_ing_detail, name="purchase_history_ing_detail"),
    path("purchase_history/end/<int:pk>/", views.purchase_history_end_detail, name="purchase_history_end_detail"),
    path('sales_history/', views.sales_history, name='sales_history'),
    path('sales_history/ing/<int:pk>/', views.sales_history_ing_detail, name='sales_history_ing_detail'),
    path('force-end-sales/<int:pk>/', views.force_end_sales, name='force_end_sales'),
    path('sales_history/end/<int:pk>/', views.sales_history_end_detail, name='sales_history_end_detail'),
    path('bid_participation/<int:pk>/', views.bid_participation, name='bid_participation'),
    path('payment/<int:pk>/', views.payment_page, name='payment_page'),
    path('payment_complete/', views.payment_complete, name='payment_complete'),
    path('auction/', views.ProductListView.as_view(), name='auction_page'),
    path('auction/<str:category>/', views.ProductListView.as_view(), name='auction_category_page'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('registrater/', views.ProductCreateView.as_view(), name='product_registrater'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/<int:pk>/like-toggle/', views.product_like_toggle, name='product_like_toggle'),
    path('liked-products/', views.liked_products, name='liked_products'),
]

orders/models.py
from django.db import models
from products.models import Product, Bid
from accounts.models import User

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from accounts.models import User
from products.models import Product, Bidder, Bid
from api.models import UserAction
from django.views.generic import ListView
from django.contrib import messages
from django.utils import timezone
from django.http import JsonResponse
import requests
from django.conf import settings
from django.core.mail import send_mail, EmailMultiAlternatives
import logging
import os
import traceback
from django.views.decorators.csrf import csrf_exempt
from dotenv import load_dotenv
load_dotenv()

# 로거 설정
logger = logging.getLogger(__name__)

#구매 - purchase
def purchase_history(request):
    purchase_product_id_list = []
    # 로그인한 유저가 구입한 상품만 가져오기
    purchase_product_ids = Bidder.objects.filter(bidder_id=request.user.id)
    for purchase_product_id in purchase_product_ids:
        purchase_product_id_list.append(purchase_product_id.product_id)
    products = Product.objects.filter(name__in=purchase_product_id_list)
    # 진행 중인 상품의 개수 계산
    in_progress_count = products.filter(product_status=True).count()
    # 진행 중인 상품 목록 조회
    in_progress_sales = products.filter(product_status=True)
    # 종료된 상품의 개수 계산
    completed_count = products.filter(product_status=False).count()
     # 종료된 상품 목록 조회
    completed_sales = products.filter(product_status=False)
    context = {
        'in_progress_sales': in_progress_sales,
        'completed_sales': completed_sales,
        'products' : products,
        'in_progress_count': in_progress_count,
        'completed_count': completed_count
    }
    return render(request, 'orders/purchase_history.html', context)

def purchase_history_ing_detail(request, pk):
    product = Product.objects.get(pk=pk)
    purchase_user = Bidder.objects.filter(product_id=pk, bidder_id=request.user.id).first()   # 사용자 희망 입찰가
    context = {
        'product' : product,
        'bid_price' : purchase_user.bid_price
    }
    return render(request, 'orders/purchase_history_ing_detail.html', context)



def purchase_history_end_detail(request, pk):
    product = Product.objects.get(pk=pk)

    fin_bid = Bid.objects.filter(product_id=pk).order_by('-bid_price').first()    # Bid 테이블에서의 해당 상품
    fin_bidder = fin_bid.bidder_id    # 해당 상품의 낙찰자 id

    current_user = request.user
    if fin_bidder == current_user.id:
        users_bid_result = '축하합니다! 경매에서 성공적으로 낙찰되었습니다.'
    else:
        users_bid_result = '이번에는 아쉽게도 낙찰되지 않았습니다. 다음 경매에서 더 나은 결과를 기대해 보세요!'
    context = {
        'product' : product,
        'users_bid_result' : users_bid_result
    }
    return render(request, 'orders/purchase_history_end_detail.html', context)


# 판매 - Sales
def sales_history(request):
    # 로그인한 유저의 행만 가져오기
    products = Product.objects.filter(seller_id=request.user.id)
    # 진행 중인 상품의 개수 계산
    in_progress_count = products.filter(product_status=True).count()
    # 진행 중인 상품 목록 조회
    in_progress_sales = products.filter(product_status=True)
    # 종료된 상품의 개수 계산
    completed_count = products.filter(product_status=False).count()
     # 종료된 상품 목록 조회
    completed_sales = products.filter(product_status=False)
    context = {
        'in_progress_count': in_progress_count,
        'completed_count': completed_count,
        'in_progress_sales': in_progress_sales,
        'completed_sales': completed_sales,
        'products' : products,
    }
    return render(request, 'orders/sales_history.html', context)


# 마이페이지 -> 판매 내역 -> 진행중 -> 하나의 상품의 상세페이지
def sales_history_ing_detail(request, pk):
    product = Product.objects.get(pk=pk)
    context = {
        'product' : product
    }
    return render(request, 'orders/sales_history_ing_detail.html', context)

# 강제 판매 종료 처리
def force_end_sales(request, pk):
    # 해당 상품 및 입찰 결과 가져오기
    product = get_object_or_404(Product, pk=pk)
    bids = Bid.objects.filter(product=product)

    # 강제 판매 종료 버튼을 눌렀을 때 필드값 변경
    if request.method == 'POST':
        product.product_status = False
        product.auction_end_time = timezone.now()
        product.present_max_bidder_price = 0
        product.present_max_bidder_id = 0
        product.save()

        # 각각의 입찰 결과를 수정하고 저장
        for bid in bids:
            bid.bid_result = False
            bid.bid_time = timezone.now()
            bid.save()

    return redirect('orders:sales_history_ing_detail', pk=pk)

# 마이페이지 -> 판매 내역 -> 진행 종료 -> 하나의 상품의 상세페이지
def sales_history_end_detail(request, pk):
    product = Product.objects.get(pk=pk)
    bid = Bid.objects.filter(product=product)

    context = {
        'product' : product,
        'bid' : bid,
    }
    return render(request, 'orders/sales_history_end_detail.html', context)


# 입찰 참여
@login_required
def bid_participation(request, pk):
    product = get_object_or_404(Product, pk=pk)
    
    if request.method == 'POST':
        price_str = request.POST.get('price')
        
        # 가격 입력값이 비어있지 않은지 확인
        if price_str.strip():
            price = int(price_str)
            
            # present_max_bid_price가 None이면 min_bid_price를 사용
            current_max_bid = product.present_max_bid_price or product.min_bid_price

            if price > current_max_bid:
                if (price - current_max_bid) % product.bid_increment == 0:
                    product.present_max_bid_price = price
                    product.present_max_bidder_id = request.user.id
                    product.save()

                    # Bidder 인스턴스 생성 및 저장
                    bidder = Bidder(
                        product_id=product,  # 외래키 연결
                        bidder_id=request.user,  # 현재 로그인한 사용자
                        bid_price=price  # 입찰 가격
                    )
                    bidder.save()  # 데이터베이스에 저장

                    # 입찰 기록
                    UserAction.objects.create(
                        user=request.user,
                        product=product,
                        action_type='bid'
                    )
                    
                    messages.success(request, '성공적으로 입찰하였습니다.')
                    return redirect('orders:payment_page', pk=product.pk)   # 결제 페이지로
                else:
                    messages.error(request, f'입찰 금액은 {product.bid_increment}원 단위로 증가해야 합니다.')
            else:
                messages.error(request, '최소입찰가보다 더 높은 가격에 입찰하여야합니다.')
        else:
            messages.error(request, '유효한 입찰가를 입력해주세요.')
    
    context = {
        'product': product
    }
    return render(request, 'orders/bid_participation.html', context)


@login_required
def payment_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'product': product
    }
    return render(request, 'orders/payment_page.html', context)


@login_required
def payment_complete(request):
    return render(request, 'orders/payment_complete.html')



class ProductListView(ListView):
    model = Product
    template_name = 'orders/auction_page.html'
    context_object_name = 'products'
    paginate_by = 10  # 페이지네이션 적용할 경우

    def get_queryset(self):
        queryset = super().get_queryset()

        # 카테고리가 있는 경우에만 필터링
        category = self.kwargs.get('category')
        if category:
            queryset = queryset.filter(category=category)

        # 정렬 기능 추가
        sort_by = self.request.GET.get('sort')
        if sort_by == 'latest':
            queryset = queryset.order_by('-auction_start_time')
        elif sort_by == 'ending_soon':
            queryset = queryset.order_by('auction_end_time')

        return queryset.filter(product_status=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.kwargs.get('category', 'All')  # 카테고리가 없으면 'All'을 기본값으로 설정
        return context
    

orders/templates/orders/auction_page.html
{% extends 'base.html' %}

{% block content %}
<style>
    #category_navbar {
        position: absolute;
        width: 255.78px;
        height: 711px;
        left: -6px;
        top: 121px;
    }

    .product-container {
        margin-left: 200px; /* 수정: 카테고리 바의 너비만큼 여백을 추가하여 목록이 겹치지 않게 함 */
        padding: 20px; /* 수정: 내부 여백 추가 */
        
    }

    .sort-buttons button {
        background-color: #f0f0f0; /* Light Gray */
        border: 1px solid #ccc; /* Light Gray */
        color: #333; /* Dark Gray */
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
    }

    .sort-buttons button:hover {
        background-color: #ddd; /* Slightly Lighter Gray */
        border-color: #bbb; /* Slightly Darker Gray */
    }

        /* 카테고리 네비게이션 바 hover 효과 */
        .navbar-nav .nav-item .nav-link:hover {
        color: #ffc107 !important; /* Bootstrap의 기본 '주황색' */
    }
</style>


<div id="category_navbar" style="display: flex;">
    <!-- 좌측 네비게이션 바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-dark" style="width: 200px; height: 100vh; flex-shrink: 0; margin-left: 40px;">
        <ul class="navbar-nav" style="color: white; flex-direction: column; margin-left: 45px; font-size: 20px; border: #333;">
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_page' %}" style="color: white;">All</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='스니커즈' %}" style="color: white;">스니커즈</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='운동화' %}" style="color: white;">운동화</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='구두' %}" style="color: white;">구두</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='부츠' %}" style="color: white;">부츠</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='플랫슈즈' %}" style="color: white;">플랫슈즈</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='로퍼' %}" style="color: white;">로퍼</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='샌들' %}" style="color: white;">샌들</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='슬리퍼' %}" style="color: white;">슬리퍼</a>
            </li>
            <li class="nav-item" style="display: flex; justify-content: center;">
                <a class="nav-link" href="{% url 'orders:auction_category_page' category='기타 신발' %}" style="color: white;">기타 신발</a>
            </li>
        </ul>
    </nav>
</div>

<div class="product-container">
    <!-- 상품 목록과 정렬 버튼을 담을 div -->
    <div style="flex-grow: 1; margin-left: 20px;">

        <!-- 카테고리명 또는 "All" 문구 -->
        <div style="text-align: center; margin-top: 20px;">
            <h2 style="font-weight: bold; font-size: 40px;">{{ category }}</h2> <!-- 수정: h3 태그를 h2로 변경하고, 글꼴 굵기와 크기 조정 -->
        </div>

        <!-- 정렬 버튼 -->
        <div class="sort-buttons" style="text-align: right; margin-bottom: 20px; ">
            <button class="btn btn-primary me-2" style="font-size: 20px;" onclick="location.href='{{ request.path }}?sort=latest'">최신순</button>
            <button class="btn btn-primary" style="font-size: 20px;"onclick="location.href='{{ request.path }}?sort=ending_soon'">마감임박순</button>
        </div>



        <!-- 상품 목록 -->
        <div class="container my-5">
          <div class="row">
              {% for product in products %}
              <div class="col-lg-3 col-md-4 col-sm-6 mb-4" style="margin-top: 40px;">
                  <div class="card h-100 shadow">
                      <a href="{% url 'products:product_detail' pk=product.pk %}">
                          <img class="card-img-top img-fluid" src="{{ product.image_url }}" alt="{{ product.name }}" style="height: 300px;">
                      </a>
                      <div class="card-body">
                          <h5 class="card-title text-center text-dark mb-3">{{ product.name }}</h5>
                      </div>
                  </div>
              </div>
              {% empty %}
              <div class="col">
                  <p class="text-center text-muted" style="font-weight: 100; font-size: 30px;">현재 해당 카테고리의 판매 중인 상품이 없습니다.</p>
              </div>
              {% endfor %}
          </div>
      </div>
    </div>
  </div>

{% endblock %}

orders/templates/orders/bid_participation.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'products/style.css' %}">


<div class="product-detail-container2">
  <div class="product-image">
      <img src="{{ product.image_url }}" alt="Product Image" class="img-fluid">
      {% if product.product_status %}
          <p id="time-remaining" class="time-remaining">경매 종료까지 남은 시간: 계산 중...</p>
      {% else %}
          <p class="time-remaining">경매가 종료되었습니다.</p>
      {% endif %}
  </div>
    {% with current_bid=product.present_max_bid_price|default_if_none:product.min_bid_price %}
    <div class="bid-product-info" data-current-bid="{{ current_bid }}" data-bid-increment="{{ product.bid_increment }}">
        <div class="info-container" style="margin-top: 11px;">
            <div class="info-item">
                <span class="info-content">{{ product.category }}</span>
            </div>
            <div class="info-item">
                <span class="info-content">{{ product.size }}</span>
            </div>
        <form class="like-item" method="post" action="{% url 'products:product_like_toggle' pk=product.pk %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button style="border:none;margin-left: 5px;">
            {% if request.user in product.likes.all %}
                <i class="far fa-heart" style="color:red; font-size: 20px;"></i>
            {% else %}
                <i class="fas fa-heart" style="color:white; font-size: 20px;"></i> 
            {% endif %}
            </button>
            <span class="like-font">
            {{ product.likes.all|length }} 명이 이 상품을 좋아합니다.
            </span>
        </form>
        </div>
        <h1>{{ product.name }}</h1>
        <p>상품 설명: {{ product.description }}</p>
        <p>경매 종료 시간: {{ product.auction_end_time }}</p>
        <form id="bid_form" action="{% url 'orders:bid_participation' product.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="product" value="{{ product.id }}">
            <input type="hidden" id="bid_price" name="price" value="">
            <h2>빠른 입찰<h2>
            <div class="quick-bid-options-content">
                <div class="quick-bid-options">
                    <button type="button" onclick="setBid(1)">₩{{ current_bid|add:product.bid_increment }}</button>
                    <button type="button" onclick="setBid(2)">₩{{ current_bid|add:product.bid_increment|add:product.bid_increment }}</button>
                    <button type="button" onclick="setBid(3)">₩{{ current_bid|add:product.bid_increment|add:product.bid_increment|add:product.bid_increment }}</button>
                </div>
            </div>
            <div class="custom-bid">
                <div class="input-wrap">
                    <input type="number" id="custom_bid_input" value="{{ current_bid|add:product.bid_increment }}" step="{{ product.bid_increment }}" class="custom-bid-input"/>
                    <div class="custom-bid-buttons">
                        <button type="button" class="increment-button" onclick="incrementValue()"></button>
                        <button type="button" class="decrement-button" onclick="decrementValue()"></button>
                    </div>
                </div>
                <button type="button" class="custom-bid-button" onclick="setCustomBid()">결제하기</button>
            </div>
        </form>
    </div>
    {% endwith %}
</div>

<script>
    // 카운트다운 할 날짜 설정
    var countDownDate = new Date("{{ product.auction_end_time|date:'Y/m/d H:i:s' }}").getTime();

    // 1초마다 카운트 다운 업데이트
    var countdownfunction = setInterval(function() {
        // 현재 날짜와 시간 가져오기
        var now = new Date().getTime();

        // 남은 시간 계산하기
        var timeRemaining = countDownDate - now;

        // 날짜, 시간, 분, 초 단위로 시간 계산
        var days = Math.floor(timeRemaining / (1000 * 60 * 60 * 24));
        var hours = Math.floor((timeRemaining % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((timeRemaining % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000);

        // id="time-remaining"인 요소에 결과 출력
        document.getElementById("time-remaining").innerHTML = "남은 시간: " + days + "일 " + hours + "시간 "
        + minutes + "분 " + seconds + "초 ";

        // 카운트 다운이 끝나면 텍스트 출력
        if (timeRemaining < 0) {
            clearInterval(countdownfunction);
            document.getElementById("time-remaining").innerHTML = "경매가 종료되었습니다";
        }
    }, 1000);

    function setBid(multiplier) {
        var container = document.querySelector('.bid-product-info');
        var base = parseInt(container.getAttribute('data-current-bid'), 10);
        var increment = parseInt(container.getAttribute('data-bid-increment'), 10);
        var newBid = base + increment * multiplier;
        document.getElementById('bid_price').value = newBid;
        document.getElementById('bid_form').submit();
    }

    function setCustomBid() {
        var customAmount = document.getElementById('custom_bid_input').value.trim();
        if (customAmount) {
            document.getElementById('bid_price').value = parseInt(customAmount, 10);
            document.getElementById('bid_form').submit();
        } else {
            alert('유효한 입찰가를 입력해주세요.');
        }
    }

    function incrementValue() {
        var input = document.getElementById('custom_bid_input');
        var step = parseInt(input.getAttribute('step'), 10);
        input.value = parseInt(input.value, 10) + step;
    }

    function decrementValue() {
        var input = document.getElementById('custom_bid_input');
        var step = parseInt(input.getAttribute('step'), 10);
        input.value = parseInt(input.value, 10) - step;
    }
</script>
{% endblock %}

orders/templates/orders/payment_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
    .payment-container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 90%; /* 너비를 화면의 90%로 설정 */
        max-width: 1200px; /* 최대 너비 제한 */
        padding: 40px; /* 내부 여백 추가 */
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 8px;
        height: 30%; /* 높이를 화면의 80%로 설정 */
        overflow-y: auto; /* 컨테이너 내부에 스크롤바 추가 */
        text-align: center; /* 내용 가운데 정렬 */
    }

    .payment-container h1 {
        margin-bottom: 20px;
        font-size: 3.0rem; /* 제목의 글꼴 크기를 더 크게 설정 */
    }

    .payment-container p {
        font-size: 1.8rem; /* 문단의 글꼴 크기를 크게 설정 */
        line-height: 1.6; /* 줄 간격 설정 */
    }

    .payment-container .btn-payment {
        width: 100%;
        background-color: #000;
        color: #fff;
        border: none;
        padding: 15px 20px; /* 버튼의 패딩을 조정하여 더 크게 보이도록 함 */
        font-size: 1.5rem; /* 버튼의 글꼴 크기를 크게 설정 */
        cursor: pointer;
        margin-top: 4%;
    }

    .payment-container .btn-payment:hover {
        background-color: #333;
    }

    .pay-text {
        font-size: 1.7rem; /* 텍스트 크기 조정 */
        font-weight: bold;
        color: black; /* 텍스트 색상 */
        display: block; /* 블록 요소로 설정하여 줄바꿈 추가 */
        margin-bottom: 10px; /* 하단 마진 추가 */
    }

    .important-text {
        font-size: 1.7rem; /* 텍스트 크기 조정 */
        font-weight: bold;
        color: #007bff; /* 텍스트 색상 */
        display: block; /* 블록 요소로 설정하여 줄바꿈 추가 */
        margin-bottom: 20px; /* 하단 마진 추가 */
    }

    @media (max-width: 768px) {
        .payment-container {
            width: 100%;
            padding: 20px;
        }
    }
</style>

<div class="container">
    <div class="payment-container">
        <h1>결제 페이지</h1>
        <p class="pay-text">아래의 버튼을 눌러 결제를 진행하세요.</p>
        <p class="important-text">경매 종료일에 최고 입찰가에 한해 자동 결제가 이루어집니다.</p>
        <div class="mt-4">
            <button type="button" class="btn btn-payment btn-lg" onclick="requestPay('{{ request.user.email }}', '{{ request.user.username }}', '{{ request.user.id }}', '{{ product.id }}')">결제하기</button>
        </div>
    </div>
</div>

<!-- 포트원 결제 -->
<script src="https://cdn.iamport.kr/v1/iamport.js"></script>
<!-- jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<!-- iamport.payment.js -->
<script type="text/javascript" src="https://cdn.iamport.kr/js/iamport.payment-1.2.0.js"></script>
<script>
    function requestPay(BuyerEmail, BuyerName, BuyerUid, ProductId) {
        var IMP = window.IMP; 
        IMP.init('imp68062031');
        var ProductName = '{{ product.name }}';

        IMP.request_pay(
            {
                pg: "kakaopay",
                pay_method: "card",
                merchant_uid: `payment-${ProductId}-${crypto.randomUUID()}`,
                name: ProductName,
                customer_uid: BuyerUid,
                buyer_email: BuyerEmail,
                buyer_name: BuyerName,
            },
            function(rsp) {
                if (rsp.success) {
                    console.log('빌링키 발급 성공', rsp);
                    alert('결제가 완료되었습니다.');
                    window.location.href = "{% url 'orders:payment_complete' %}";
                } else {
                    var msg = "결제에 실패했습니다: ";
                    msg += rsp.error_msg;
                    alert(msg);
                }
            }
        );
    }
</script>
{% endblock %}

orders/templates/orders/purchase_history_end.html
{% block content %}
<style>
    a {
        text-decoration-line: none;
        color: inherit;
    }

    .row {
    width: 1200px; 
    margin: 0 auto;
    }

    .food-image {
    width: 100%; /* 원하는 너비로 설정 */
    height: 400px; /* 원하는 높이로 설정 */
    object-fit: cover; /* 이미지를 요소에 맞게 자르거나 늘리도록 설정 */
    }

    .card-title {
    height: 50px;
    }

</style>
{% if completed_sales %}
<div class='row'>
<div class="col-md-12 text-center">
    <div class="row">
        {% for object in completed_sales %}
            <div class="col-sm-6 col-md-4 mb-4">
                <div class="card">
                    <a href="{% url 'orders:purchase_history_end_detail' object.id %}">
                        <img src="{{ object.image_url }}" class="card-img-top food-image" alt="{{ object.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name }}</h5>
                            
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>
{% else %}
    <p>진행이 완료된 상품이 없습니다.</p>
{% endif %}
{% endblock %}