api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserActionViewSet, ProductViewSet, BidViewSet, UserViewSet, recommend_products

router = DefaultRouter()
router.register(r'useractions', UserActionViewSet)
router.register(r'product', ProductViewSet)
router.register(r'bid', BidViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('recommend/<int:user_id>/', recommend_products, name='recommend_products'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

#거래내역 ( 등록중 상품 목록, 입찰 참여중 상품 목록, 입찰 완료 상품 목록)
#(상품 등록) -> 등록중 상품 목록에 추가
#입찰 참여 - > 입찰가 입력 (-> 마일리지 차감) -> 입찰 참여중 목록에 올라감(product table 참조)
#입찰 완료 -> Bid 테이블에 새로운 행 생성 -> 입찰 완료 상품 목록에 추가 
urlpatterns = [
    path('purchase_history/', views.purchase_history, name='purchase_history'),
    path("purchase_history/ing/<int:pk>/", views.purchase_history_ing_detail, name="purchase_history_ing_detail"),
    path("purchase_history/end/<int:pk>/", views.purchase_history_end_detail, name="purchase_history_end_detail"),
    path('sales_history/', views.sales_history, name='sales_history'),
    path('sales_history/ing/<int:pk>/', views.sales_history_ing_detail, name='sales_history_ing_detail'),
    path('force-end-sales/<int:pk>/', views.force_end_sales, name='force_end_sales'),
    path('sales_history/end/<int:pk>/', views.sales_history_end_detail, name='sales_history_end_detail'),
    path('bid_participation/<int:pk>/', views.bid_participation, name='bid_participation'),
    path('payment/<int:pk>/', views.payment_page, name='payment_page'),
    path('payment_complete/', views.payment_complete, name='payment_complete'),
    path('auction/', views.ProductListView.as_view(), name='auction_page'),
    path('auction/<str:category>/', views.ProductListView.as_view(), name='auction_category_page'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('registrater/', views.ProductCreateView.as_view(), name='product_registrater'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/<int:pk>/like-toggle/', views.product_like_toggle, name='product_like_toggle'),
    path('liked-products/', views.liked_products, name='liked_products'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}발바닥 옥션{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    {% block extra-style %}
    <style>
        .logo img {
            height: 80px; /* 로고 이미지 높이 설정 */
            width: 100px; /* 가로 크기는 자동 조정 */
        }

        .logo {
            position: absolute; /* 로고 위치를 절대 위치로 설정 */
            top: 0; /* 화면 상단에 위치 */
            left: 0; /* 화면 좌측에 위치 */
            padding: 10px; /* 로고 주변 여백 설정 */
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #f8f9fa; /* 푸터 배경색 지정 */
            padding: 20px 0; /* 푸터 내부 여백 설정 */
            text-align: center; /* 푸터 내용 가운데 정렬 */
        }
        .content{
          width: 100%;
          height: 100%;
          min-height: 1200px;
          max-height: 1400px;
          margin: 0 auto; /* 가운데 정렬을 위한 자동 마진 설정 */
          padding: 60px; /* 내부 패딩 설정 */
          box-sizing: border-box; /* 패딩 포함한 전체 너비 지정 */
          position: relative;
        }
    </style>
   {% endblock %}
</head>

<body>
    <!-- 상단 로고와 사이트 명, 네비게이션 바 -->
    <header>
        <nav>
            {% include 'navbar.html' %}
        </nav>
    </header>
    
    <!-- 내용을 담는 부분 -->
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
      <div class="container">
          <p>&copy; 2024 발바닥 옥션. All rights reserved.</p>
      </div>
    </footer>
    
    <!-- Bootstrap JS with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'home/style.css' %}">

<!-- 배너 섹션 -->
<section class="banner">
    <div class="container">
        <!-- 배너 내용 추가 -->
        <div class="banner-text">CUSTOMIZE YOUR SHOES, CUSTOMIZE YOUR VALUE 
          신발의 가치를 커스텀하다.</div>
    </div>
</section>

<div class="container">
  {% if request.user.is_authenticated and recommended_products %}
  <!--추천 상품 섹션-->
  <section class="recommended-products" style="margin-top: 60px;">
    <h2 class="category-title">추천 상품</h2>
      <div class="row">
          {% for product in recommended_products|slice:":3" %}
          <div class="col-md-4 mb-6">
              <div class="card">
                  <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
                  <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
      <a href="{% url 'orders:auction_page' %}" class="btn more-btn mt-3">더 보기</a>
    </section>

    <hr>


  <!-- 인기 상품 섹션 -->
  <section class="popular-products">
   {% else %}
  <section class="popular-products" style="margin-top: 50px; margin-bottom: 80px;">
    {% endif %}
    <h2 class="category-title">인기 상품</h2>
      <div class="row">
          {% for product in popular_products|slice:":3" %}
          <div class="col-md-4 mb-6">
              <div class="card">
                  <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
                  <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
  <a href="{% url 'orders:auction_category_page' category='스니커즈' %}" class="btn more-btn mt-3">더 보기</a>
  </section>

  <hr>

<!-- 스니커즈 섹션 -->
<section class="category-section">
  <h2 class="category-title">스니커즈</h2>
  <div class="row">
      {% for product in sneakers|slice:":3" %}
      <div class="col-md-4 mb-6">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='스니커즈' %}" class="btn more-btn mt-3">더 보기</a>
</section>

<hr>

<!-- 운동화 섹션 -->
<section class="category-section">
  <h2 class="category-title">운동화</h2>
  <div class="row">
      {% for product in athletic_shoes|slice:":3" %}
      <div class="col-md-4">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='운동화' %}" class="btn more-btn mt-3">더 보기</a>
</section>

<hr>

<!-- 부츠 섹션 -->
<section class="category-section">
  <h2 class="category-title">부츠</h2>
  <div class="row">
      {% for product in boots|slice:":3" %}
      <div class="col-md-4">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='부츠' %}" class="btn more-btn mt-3">더 보기</a>
</section>

<hr>

<!-- 플랫슈즈 섹션 -->
<section class="category-section">
  <h2 class="category-title">플랫슈즈</h2>
  <div class="row">
      {% for product in flats|slice:":3" %}
      <div class="col-md-4">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='플랫슈즈' %}" class="btn more-btn mt-3">더 보기</a>
</section>

<hr>

<!-- 로퍼 섹션 -->
<section class="category-section">
  <h2 class="category-title">로퍼</h2>
  <div class="row">
      {% for product in loafers|slice:":3" %}
      <div class="col-md-4">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='로퍼' %}" class="btn more-btn mt-3">더 보기</a>
</section>

<hr>

<!-- 샌들 섹션 -->
<section class="category-section">
  <h2 class="category-title">샌들</h2>
  <div class="row">
      {% for product in sandals|slice:":3" %}
      <div class="col-md-4">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='샌들' %}" class="btn more-btn mt-3">더 보기</a>
</section>

<hr>

<!-- 슬리퍼 섹션 -->
<section class="category-section">
  <h2 class="category-title">슬리퍼</h2>
  <div class="row">
      {% for product in slippers|slice:":3" %}
      <div class="col-md-4">
          <div class="card">
              <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
              <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <a href="{% url 'products:product_detail' pk=product.pk %}" class="btn btn-primary detail-btn">자세히 보기</a>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
  <a href="{% url 'orders:auction_category_page' category='슬리퍼' %}" class="btn more-btn mt-3">더 보기</a>
</section>
<hr>

</div>
{% endblock %}

templates/navbar.html
{% load static %}
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a href="{% url 'index' %}">
      <img src="{% static 'images/main_logo.png' %}" alt="Site Logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
            <a class="nav-link" href="{% url 'orders:auction_page' %}">Auction</a>
          </li>
          <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
            <a class="nav-link" href="{% url 'products:product_registrater' %}">Registration</a>
          </li>
          <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
            <a class="nav-link" href="{% url 'products:liked_products' %}">Like</a>
          </li>
          <!-- 사용자 인증 여부에 따라 로그인/회원가입 또는 마이페이지/로그아웃 버튼 표시 -->
          {% if user.is_authenticated %}
              <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
                <a class="nav-link" href="/accounts/mypage/">My Page</a>
              </li>
              <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
                <a class="nav-link" href="/accounts/logout/">Logout</a>
              </li>z
          {% else %}
              <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
                <a class="nav-link" href="/accounts/login/">Login</a>
              </li>
              <li class="nav-item" style="margin-left: 30px; font-size: 25px;">
                <a class="nav-link" href="/accounts/register/">Join</a>
              </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>